name: Build and Push to ECR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set version to short commit SHA
        run: |
          shortSha=$(git rev-parse --short "${{ github.sha }}")
          echo "VERSION=$shortSha" >> "$GITHUB_ENV"

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false # Avoid warning: https://github.com/actions/setup-go/issues/403

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.arch }} go build -ldflags "-s -w -X main.version=${{ env.VERSION }}" -trimpath -o route53-sidecar

      - name: Configure AWS Credentials for CI
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::488659951590:role/ci-role-d4fe904 # ciRoleArn from defang-io/infrastructure stack

      - name: Configure AWS Credentials for Staging
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::426819183542:role/admin # adminUserRoleArn from defang-io/bootstrap stack
          role-duration-seconds: 1200
          role-chaining: true

      - name: Log in to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7
        with:
          registry-type: public

      - name: Build and push Docker image
        run: |
          ECR_PUBLIC_IMAGE_NAME=public.ecr.aws/defang-io/route53-sidecar
          IMAGE_TAG=${{ matrix.arch }}-${{ env.VERSION }}
          docker build --platform linux/${{ matrix.arch }} -t route53-sidecar -t $ECR_PUBLIC_IMAGE_NAME:$IMAGE_TAG .
          docker push $ECR_PUBLIC_IMAGE_NAME:$IMAGE_TAG

  manifest:
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set version to short commit SHA
        run: |
          shortSha=$(git rev-parse --short "${{ github.sha }}")
          echo "VERSION=$shortSha" >> "$GITHUB_ENV"

      - name: Configure AWS Credentials for CI
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::488659951590:role/ci-role-d4fe904 # ciRoleArn from defang-io/infrastructure stack

      - name: Configure AWS Credentials for Staging
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::426819183542:role/admin # adminUserRoleArn from defang-io/bootstrap stack
          role-duration-seconds: 1200
          role-chaining: true

      - name: Log in to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7
        with:
          registry-type: public

      - name: Create and push Docker manifest
        run: |
          ECR_PUBLIC_IMAGE_NAME=public.ecr.aws/defang-io/route53-sidecar
          VERSION=${{ env.VERSION }}
          docker manifest create $ECR_PUBLIC_IMAGE_NAME:$VERSION \
            --amend $ECR_PUBLIC_IMAGE_NAME:amd64-$VERSION \
            --amend $ECR_PUBLIC_IMAGE_NAME:arm64-$VERSION
          docker manifest create $ECR_PUBLIC_IMAGE_NAME:latest \
            --amend $ECR_PUBLIC_IMAGE_NAME:amd64-$VERSION \
            --amend $ECR_PUBLIC_IMAGE_NAME:arm64-$VERSION
          docker manifest push --purge $ECR_PUBLIC_IMAGE_NAME:$VERSION
          docker manifest push --purge $ECR_PUBLIC_IMAGE_NAME:latest
